### ISSUE TITLE
LTI authentication feature

### ISSUE THREAD

**Issue by ferishili** [unirz-tu-ilmenau/moodle-filter_opencast#52]
As decided in the core group, we now can have LTI authentication and LTI launch forms in this plugin to benefit from the only possible way of authentication offered by Opencast at the moment.

**Comment by ferishili** [comment]
A very important PR from Opencast that we need to pay attention to regarding this:
https://github.com/elan-ev/opencast_nginx/pull/5

**Comment by bluetom** [comment]
You mean we do use cookies outside the Moodle core conventions in the opencast plugins and the plugins have to take care of that problem by themself?

**Comment by ferishili** [comment]
It is the suggestion Nginx configuration that needs to be applied in Opencast Server itself, which allows LTI authenthication to work properly in all major web browsers.
So if some institution is willing to use LTI authenthication properly, they would need to apply this setting in their Opencast Nginx server (or Apache).

**Comment by mtneug** [comment]
@ferishili this is not implemented in Safari. And the setting in nginx is really also only a hack, But yes, `Partitioned` would solve the LTI use case. In the long term, I'm still favoring only supporting JWT and getting rid of LTI in the Moodle plugins.

**Comment by ferishili** [comment]
@mtneug, great, thanks for your feedback. And I agree and also in favor of switching to JWT for all LMSes but when it is 100% functional! So this would be a good solution of providing more security for now!
